### ISSUE TITLE
Frontend message type missing variants

### ISSUE THREAD

**Issue by coder543** [jackc/pgproto3#14]
This library has been really nice to work with so far! I just noticed one or two small things, and figured I would open this issue.

According to the [message formats page](https://www.postgresql.org/docs/13/protocol-message-formats.html), `CopyData` should be both a frontend and backend message type.

Right now, `pgproto3` only seems to implement it as a backend message. I think `CopyDone` is similarly missing from the frontend message type.

I could be misreading the Postgres documentation.

**Comment by jackc** [comment]
It's already on master it just wasn't in a release yet. Just tagged `v2.0.7` which includes it.

**Comment by coder543** [comment]
Thanks!
