### ISSUE TITLE
Correct usage for different message formats

### ISSUE THREAD

**Issue by johnernaut** [jackc/pgproto3#28]
This issue is more of a question around usage rather than a bug being present.  If that's not ok, I'd be happy to close this.  I am using `pgproto3` to act as a fake PG server to respond to [ActiveRecord](https://guides.rubyonrails.org/active_record_basics.html) (ORM) queries.  I have my message handling on the `pgproto3` side set up like the following (with the `pgproto3.Query` type matching the example in this repo almost exactly):

```go
for {
	   msg, err := backend.Receive()
	   // ... err handling

	   switch msg.(type) {
	   case *pgproto3.Parse:
			 fmt.Printf("received parse from client: %#v", msg)
			 buf := (&pgproto3.ParseComplete{}).Encode(nil)
			 _, err = conn.Write(buf)
			 if err != nil {
				   return fmt.Errorf("error writing parse response: %w", err)
			 }
	   case *pgproto3.Bind:
			 fmt.Printf("received bind from client: %#v", msg)
			 buf := (&pgproto3.BindComplete{}).Encode(nil)
			 _, err = conn.Write(buf)
			 if err != nil {
				   return fmt.Errorf("error writing parse response: %w", err)
			 }
	   case *pgproto3.Execute:
			 fmt.Printf("received execute from client: %#v", msg)
			 buf := (&pgproto3.Execute{Portal: "", MaxRows: 0}).Encode(nil)
			 buf = (&pgproto3.ReadyForQuery{TxStatus: 'I'}).Encode(buf)
			 _, err = conn.Write(buf)
			 if err != nil {
				   return fmt.Errorf("error writing parse response: %w", err)
			 }
	   case *pgproto3.Describe:
			 fmt.Printf("received describe from client: %#v", msg)
			 // similar code as execute / bind
	   case *pgproto3.Sync:
			 fmt.Printf("received sync from client: %#v", msg)
			 // similar code as the above cases
	   case *pgproto3.Query:
                        // mostly matches the code in the example repo
... other stuff...
}
```

ActiveRecord sends some queries that fall under the `Bind`, `Execute`, `Parse`, etc... scopes in the cases above, but the problem is I'm not exactly sure how I should go about responding to those different cases via the `Write` command, or if I should be using `Write` at all for those cases.  Here's an example ActiveRecord error log when trying to run a query:

```shell
ActiveRecord::StatementInvalid: PG::UnableToSend: no error message available
message contents do not agree with length in message type "E"

from /lib/ruby/gems/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `exec_params'
Caused by PG::UnableToSend: no error message available
message contents do not agree with length in message type "E"

from /lib/ruby/gems/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `exec_params
```
Some of the queries the ORM automatically sends when connecting look like this:
```sql
SELECT t.oid, t.typname FROM pg_type as t WHERE t.typname IN ('int2', 'int4', 'int8', 'oid', 'float4', 'float8', 'numeric', 'bool', 'timestamp', 'timestamptz');
SET SESSION timezone TO 'UTC';
SET client_min_messages TO 'warning';
```

I know that a random ORM project isn't within the realm of what people here are expected to understand, but I thought someone may be able to point me in the right direction here.  Thanks!

**Comment by jackc** [comment]
At a rough glance it looks okay. But you might want to look at https://github.com/jackc/pgmock. In particular, the `pgmockproxy` demo. You could use that to observe the message flow between your client and the PG server to see what is expected.

**Comment by johnernaut** [comment]
@jackc ah, thanks for the tip!  I'll give that a shot.
