### ISSUE TITLE
psycopg2 issue connecting due to: psycopg2.OperationalError: server didn't return client encoding

### ISSUE THREAD

**Issue by mikeggh** [jackc/pgproto3#32]
example using fortune server in ~/go/pkg/mod/github.com/jackc/pgproto3/v2@v2.2.0/example/pgfortune:
go run main.go server.go -listen 0.0.0.0:15432
2023/04/04 20:06:10 Listening on 0.0.0.0:15432
2023/04/04 20:06:13 Accepted connection from 192.168.1.11:50252
2023/04/04 20:06:13 Closed connection from 192.168.1.11:50252

python3
import psycopg2
conn = psycopg2.connect("postgresql://127.0.0.1:15432")

I tried to force client_encoding with no success like this:
postgresql://127.0.0.1:15432?client_encoding=utf8

The real error:
  conn = psycopg2.connect("postgresql://127.0.0.1:15432")
  File "/home/user/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: server didn't return client encoding

Are there any quick solutions to this scenario?

**Comment by jackc** [comment]
You might want to use the pgproto3 in the pgx repository. That is where active development is taking place now.

That said, I think the solution would be for `(p *PgFortuneBackend) handleStartup()` to send a `ParameterStatus` message for client encoding.

**Comment by mikeggh** [comment]
ok thanks for the response, ill check both out.. I'll post back later seeing if my minimal go skills can get something going here, otherwise I'll try to move to the newer.. This was originally to get postlite to work (go project serving a data directory of multiple sqlites as postgres wire protocol).
