### ISSUE TITLE
Format list of values and meaning in FieldDescriptions 

### ISSUE THREAD

**Issue by syacko** [jackc/pgproto3#6]
I have reviewed the FieldDescription struct and was unable to determine the usage of the format. I was hoping it could be used for determining the output format (string or int) for some utilities that I'm working on for data. When I review the values, I see a value of 0 and 1. Comparing them to int and string based (varchar) fields in the database, they don't always match. If there is documentation, I was not able to find it. Any insight on the field and whether it should be used for my purpose would be great.

**Comment by jackc** [comment]
See https://www.postgresql.org/docs/current/protocol-message-formats.html. The `FieldDescription` represents the field part of the `RowDescription` message.

**Comment by syacko** [comment]
Thank you
